# Generated by Django 5.2.10 on 2026-01-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('raw_payload', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
