# Generated by Django 5.2.10 on 2026-01-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cverecord',
            name='fetched_at',
        ),
        migrations.AddField(
            model_name='cverecord',
            name='last_modified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cverecord',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cverecord',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cverecord',
            name='cve_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cverecord',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cverecord',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
